### ISSUE TITLE
Not sure how to use custom filters

### ISSUE THREAD

**Issue by teampl4y4** [adesigns/calendar-bundle#35]
I have several events that belong to different "owners".  So I am trying to figure out how to load only the events for the current "owner", and assume I need to use the custom filter option in eventSources: [ { but, I can't for the life of me figure out how that works?  Is there any example code or documentation I can look at?

**Comment by mikeyudin** [comment]
I'm sure this is way off your radar now, but for future reference, you would set up eventSources as described here: https://github.com/adesigns/calendar-bundle#extending-the-calendar-javascript, and then read the filters by passing the Request object into your event listeners and retrieving the filters via parameters.
