### ISSUE TITLE
I can not show the events in the calendar

### ISSUE THREAD

**Issue by h00dstoker** [adesigns/calendar-bundle#37]
$calendarEvent->addEvent($eventEntity);
var_dump($calendarEvent->getEvents());exit;

object(Doctrine\Common\Collections\ArrayCollection)[2277]
  private 'elements' => 
    array (size=1)
      0 => 
        object(ADesigns\CalendarBundle\Entity\EventEntity)[2342]
          protected 'id' => null
          protected 'title' => string 'Primeira fase' (length=13)
          protected 'url' => string 'http://www.google.com' (length=21)
          protected 'bgColor' => string '#FF0011' (length=7)
          protected 'fgColor' => string '#FFFFFF' (length=7)
          protected 'cssClass' => string 'my-custom-class' (length=15)
          protected 'startDatetime' => 
            object(DateTime)[2321]
              ...
          protected 'endDatetime' => 
            object(DateTime)[2340]
              ...
          protected 'allDay' => boolean false
          protected 'otherFields' => 
            array (size=0)
              ...

I have events but they are not in the calendar display

**Comment by mikeyudin** [comment]
I'd need more information.  Sounds like your calendar is not set up correctly.  Based on the age of this issue, closing.
