### ISSUE TITLE
Symfony3

### ISSUE THREAD

**Issue by bettinz** [adesigns/calendar-bundle#42]
Hello, do you plan to make it compatible with symfony3?

Thank you

**Comment by krlove** [comment]
I have the same question.

**Comment by elvismdev** [comment]
+1

**Comment by mikeyudin** [comment]
Yes, will have this out to you guys in a couple days, along with some other PR merges.

**Comment by mikeyudin** [comment]
Hey all,

I have added symfony 3 support in #43.  Please update your dependencies to the `"adesigns/calendar-bundle": "1.1.1"` tag for symfony 3 support, as I will be upgrading the master branch heavily soon to allow for the latest version of FullCalendar, which I don't believe will be backwards compatible.
