### ISSUE TITLE
Routing is not defined error

### ISSUE THREAD

**Issue by Pablossoo** [adesigns/calendar-bundle#45]
Hello, I tried load your bundle, but after do all steps, my console return this error? why?

**Comment by dmatora** [comment]
Having same problem.
@Pablossoo have you solved it?

**Comment by mikeyudin** [comment]
@dmatora Have you added, enabled, and configured the FOSJsRouting bundle?

**Comment by dmatora** [comment]
yeah, that solved it, thank you

**Comment by nataliastanko** [comment]
It helped me too.
