### ISSUE TITLE
Show end date or event height based on duration

### ISSUE THREAD

**Issue by bettinz** [adesigns/calendar-bundle#46]
Hello, I'm using your bundle (v 2) and it works great. Thank you!
I want to show end time on event name in calendar or to manage event height based on duration (ex. 1 row for 6 hours, 2 row for 12 hours, 4 row is all day).
Is that possible?

Also, is possible to set 24 hours format for time?

Thank you

**Comment by mikeyudin** [comment]
These are all configuration options for Full Calendar (http://fullcalendar.io/docs/).  This bundle just links the symfony backend to FullCalendar client-side library.  You'll need to override the calendar-settings.js file in this bundle to configure FullCalendar differently than the defaults.
