### ISSUE TITLE
Issue with appProdDebugProjectContainer after deployment

### ISSUE THREAD

**Issue by Organicdareal** [adesigns/calendar-bundle#51]
Hi, i've been using the calendar-bundle for several months, without any problem until now : 

Everything works great on my dev server (dev & prod), but after a new deployment (with capistrano) today on my prod server, the listener for events isn't called. Instead i got a 500 error on fc-load-events with this stack : 

`Catchable Fatal Error: Argument 2 passed to MIP\CRMBundle\EventListener\CalendarEventListener::__construct() must be an instance of Symfony\Component\Security\Core\SecurityContext, instance of appProdDebugProjectContainer given, called in /var/www/mip-test/releases/20161108094641/app/cache/prod/appProdDebugProjectContainer.php on line 3837 and defined`

I didn't change anything on the calendar, and it's still working on dev server. Here's what I've got in services.yml : 

`services:
  lab.bundle.calendar_listener:
    class: MIP\CRMBundle\EventListener\CalendarEventListener
    arguments: ["@doctrine.orm.entity_manager",  "@security.context", "@service_container"]
    tags:
        -  { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }`

I didn't have any problem before, the listener was working fine a few days ago, and i didn't change anything about it... It seems like the issue is coming from the cache in the releases folder, but what could be wrong ?

**Comment by Organicdareal** [comment]
Someone ????

**Comment by mikeyudin** [comment]
There have been no updates to the bundle recently.  Sounds like something is wrong with your service configuration.  Additionally, The CalendarEventListener you have described is not part of the CalendarBundle, so it wouldn't have anything to do with this bundle.
