### ISSUE TITLE
Does Calendar Bundle work on Symfony3? 

### ISSUE THREAD

**Issue by cobuntu** [adesigns/calendar-bundle#52]
Hello, 

i start a new project and we have to decide to choice between symfony 2 or 3. Do you know if this bundle work on symfony3?
Thanks

**Comment by mikeyudin** [comment]
Yes, this bundle works with symfony 3.  Any new project you start should use Symfony 3 unless you have a **very** good reason not to.  

As a tip, you can check any bundle's composer.json file to see the dependencies.  In this bundle, you'll notice the line `"symfony/framework-bundle": "~2.1|~3.0",`  which means we support symfony 2.x and 3.x.

Good luck!
