### ISSUE TITLE
Full Calendar Symfony the route fullcalendar_loader does not exist

### ISSUE THREAD

**Issue by LunarNights** [adesigns/calendar-bundle#54]
Hi guys,

I've been trying to install the Full Calendar Bundle and have done every step but I get an javascript error that says that the route fullcalendar_loader does not exist. Why is this? I have also installed fosJsRouting.

**Comment by mikeyudin** [comment]
You may need to run the assets:install command to dump the javascript from the vendor directory to your public assets folder.  That's the first thing that comes to mind.  Should work out of the box following the instructions otherwise.

**Comment by LunarNights** [comment]
Hi,

Thanks for reacting I've done the assets:install but I still get the error, I definitely think it has something to do with the fosjsrouting but I don't know why.

**Comment by LunarNights** [comment]
here is a pic. 
![error](https://cloud.githubusercontent.com/assets/24652245/24492933/41b47df2-152d-11e7-89ea-9cf8026c4675.JPG)

**Comment by LunarNights** [comment]
Could it be that I first installed the fullcalendar bundle and then the fosjsrouting?

**Comment by LunarNights** [comment]
Fixed the problem!

The problem was that I first installed the calendar bundle and then the fosjsrouting bundle, so I first had to remove the calendarbundle and install it again I also had to use the calendar js all the way on the bottom of  my view.
