### ISSUE TITLE
Events not loading after composer update

### ISSUE THREAD

**Issue by sarannrich** [adesigns/calendar-bundle#60]
I have been using your calendar bundle for a while now and it's been working fine until I did a `composer update` a few days ago.

Please see the link below for more details.

https://stackoverflow.com/questions/45323449/adesigns-calendarbundle-events-not-showing-after-composer-update 

below is a copy of my composer.json

	"require" : {
		"php" : "7.0.18",
		"adesigns/calendar-bundle" : "^1.1",
		"catfan/Medoo" : "^1.1",
		"doctrine/common" : "^2.7",
		"doctrine/dbal" : "^2.5",
		"doctrine/doctrine-bundle" : "^1.6",
		"doctrine/doctrine-cache-bundle" : "^1.2",
		"doctrine/orm" : "^2.5",
		"friendsofsymfony/jsrouting-bundle" : "^1.6",
		"incenteev/composer-parameter-handler" : "^2.0",
		"knplabs/knp-menu-bundle" : "^2.1",
		"mopa/bootstrap-bundle" : "^3.1",
		"pimple/pimple" : "^3.0",
		"sensio/distribution-bundle" : "^5.0",
		"sensio/framework-extra-bundle" : "^3.0.2",
		"sensio/generator-bundle" : "^3.1",
		"symfony/symfony" : "3.3.x-dev",
		"symfony/swiftmailer-bundle" : "^2.3",
		"symfony/monolog-bundle" : "^2.8",
		"symfony/polyfill-apcu" : "^1.0",
		"twig/twig" : "~1.0",
		"twbs/bootstrap" : "^3.3",
		"php-imap/php-imap" : "^2.0",
		"egeloen/google-map-bundle" : "^3.0",
		"knplabs/knp-paginator-bundle" : "^2.5",
		"akeneo-labs/spreadsheet-parser" : "^1.2"
	},

**Comment by mikeyudin** [comment]
When was the last time you did a composer update?

**Comment by sarannrich** [comment]
An hour or so ago.

**Comment by sarannrich** [comment]
Because the project is still in development I do a composer update at least once every two days.

**Comment by mikeyudin** [comment]
If the calendar was working, but a composer update broke it, something outside of the bundle must have caused it, as the bundle has not changed at all recently.  Let's start by trying a specific version -- change `"^1.1"` to `"1.1.1"`, just to rule out that you're not using `1.2-beta`.

**Comment by sarannrich** [comment]
Changed composer.json `"adesigns/calendar-bundle" : "1.1.1",`.
Ran `composer update -o` which also calls `cache:clear`.
There were no changes to the calendar bundle during the update.

I still can't see the events on the calendar

**Comment by mikeyudin** [comment]
Can you revert your code base back to before you did a composer update, run
composer install to put back your old dependencies?  I know thats not
optimal, but really hard to diagnose this since nothing has changed on our
end.

**Comment by sarannrich** [comment]
My apologies it wasn't an update issue but a data one. Some `NULL` dates had been entered which was causing errors.
I was only able to see the errors after rebasing and doing a `composer install`
Thanks for your help though.

**Comment by mikeyudin** [comment]
No problem, happy to help.
